### ISSUE TITLE
Preprocessing of input data

### ISSUE THREAD

**Issue by shardulparab97** [tiongleslie/DSCNN_OCLBCP#1]
The paper was definitely an amazing read and the results too look very promising for future work.

Would like to know about the preprocessing (normalization, etc) and augmentations(if any) applied to the RGB and texture(OC-LBCP) images before being input to the Dual Stream Network(with shared weights).

Thank you.

**Comment by tiongleslie** [comment]
Hi shardulparab97,

Yeah, the normalization is applied.
Please refer to line 85 in image_utisl.py.

Thanks.
